### ISSUE TITLE
[BUG] train_numpy() got multiple values for argument 'feature_types' - dgan 

### ISSUE THREAD

**Issue by jankrans** [gretelai/gretel-synthetics#133] opened 2022-11-23 15:29 UTC
I was trying to run the example code of dgan. But I keep getting the same errors and can't really understand where it's going wrong...

The code comes from: https://github.com/gretelai/public_research/blob/main/oss_doppelganger/sample_usage.ipynb

```
import numpy as np
import pandas as pd

from gretel_synthetics.timeseries_dgan.dgan import DGAN
from gretel_synthetics.timeseries_dgan.config import DGANConfig, OutputType, Normalization

attributes = np.random.randint(0, 3, size=(1000,3))
features = np.random.random(size=(1000,20,2))

model = DGAN(DGANConfig(
    max_sequence_len=20,
    sample_len=4,
    batch_size=1000,
    epochs=10,  # For real data sets, 100-1000 epochs is typical
))

model.train_numpy(
    attributes, features,
    attribute_types = [OutputType.DISCRETE] * 3,
    feature_types = [OutputType.CONTINUOUS] * 2
)

synthetic_attributes, synthetic_features = model.generate_numpy(1000)
```
This code produces the following error:

```
~\AppData\Local\Temp\ipykernel_19824\3379362806.py in <module>
     19     attributes, features,
     20     attribute_types = [OutputType.DISCRETE] * 3,
---> 21     feature_types = [OutputType.CONTINUOUS] * 2
     22 )
     23 

TypeError: train_numpy() got multiple values for argument 'feature_types'

```

Miniconda3 with following libs installed with pip (used with jupyter notebook wihtinn VScode)
- python: 3.7.15
- greta-synthetics: 0.19.0
- numpy: 1.21.6

**Comment by kboyd** [comment] 2022-11-23 17:56
I'm guessing a bit since the full stack trace is truncated, but the order of arguments to `train_numpy` looks wrong. That example usage and actual code are out of sync I think. Thanks for including the link so I can confirm and get it fixed right away.

Try the following line for the `train_numpy` call using keyword args instead:
```
model.train_numpy(attributes=attributes, features=features)
```

And this also explains that original error you saw too. From the current [source code](https://github.com/gretelai/gretel-synthetics/blob/7187b0e3c72ac71f643e6d7eeba863cc4c5aef17/src/gretel_synthetics/timeseries_dgan/dgan.py#L142) (which should be exactly what's in version 0.19.0),

```
    def train_numpy(
        self,
        features: np.ndarray,
        feature_types: Optional[List[OutputType]] = None,
        attributes: Optional[np.ndarray] = None,
        attribute_types: Optional[List[OutputType]] = None,
    ):
```

So in your opening post, replacing the positional args with keyword versions from the order above, the function call was:
```
model.train_numpy(
    features=attributes, feature_types=features,
    attribute_types = [OutputType.DISCRETE] * 3,
    feature_types = [OutputType.CONTINUOUS] * 2
)
```
Hence the error about `feature_types` given twice.

**Comment by kboyd** [comment] 2022-12-02 00:03
https://github.com/gretelai/public_research/pull/4 fixes function calls in the `sample_usage.ipynb` notebook.

**Comment by kboyd** [comment] 2022-12-06 23:08
Notebook examples are updated now. Thanks for making us aware of these outdated examples!

Closing this issue. Please reopen if there are further problems running the example code.

**Closed by kboyd** 2022-12-06 23:08 UTC
